import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        canvas: '#0A0A0A',
        'surface-1': '#121212',
        'surface-2': '#1E1E1E',
        'surface-3': '#2A2A2A',
        'surface-4': '#161616',
        'surface-container-low': '#1c1b1b',
        'surface-container-high': '#2a2a2a',
        'surface-container-highest': '#353534',
        'surface-container-lowest': '#0e0e0e',
        'stroke': '#3F3F46',
        'saffron': '#FF671F',
        'saffron-dark': '#FF671F',
        'saffron-hover': '#E05A1B',
        'india-green': '#138808',
        'india-green-dark': '#046A38',
        'navy': '#002868',
        'accent-blue': '#3B82F6',
        'accent-blue-light': '#60A5FA',
        'primary-container': '#FF671F',
        'secondary-container': '#006836',
        'error': '#ffb4ab',
        'error-container': '#93000a',
        'on-surface': '#e5e2e1',
        'on-surface-variant': '#e2bfb2',
        'outline': '#a98a7e',
        'text-primary': '#FFFFFF',
        'text-body': '#E5E7EB',
        'text-secondary': '#A1A1AA',
        'text-muted': '#71717A',
        'text-blue': '#60A5FA',
        'border-default': '#2A2A2A',
        'border-active': '#3F3F46',
      },
      fontFamily: {
        sans: ['"Roboto Flex"', '"Open Sans"', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'label-md': ['0.75rem', { lineHeight: '1rem', letterSpacing: '0.05em', fontWeight: '500' }],
        'label-lg': ['0.875rem', { lineHeight: '1.25rem', letterSpacing: '0.05em', fontWeight: '500' }],
        'label-mono-security': ['0.625rem', { lineHeight: '0.75rem', letterSpacing: '0.12em', fontWeight: '600' }],
      },
      borderRadius: {
        'sm': '0.125rem',
        'DEFAULT': '0.25rem',
        'md': '0.375rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
      },
      spacing: {
        'gutter': '1.5rem',
        'gutter-mobile': '1rem',
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2.5rem',
      },
    },
  },
  plugins: [],
};
export default config;
