from __future__ import annotations

import asyncio
import uuid
import traceback
from app.graph.orchestrator import build_simulation_graph
from app.graph.state import SimState
from app.core.redis import get_redis_pool, publish_run_event
from app.core.database import async_session_maker
from app.models.run import SimulationRun

async def start_simulation(run_id: str) -> None:
    """Trigger LangGraph pipeline and publish SSE events."""
    redis = await get_redis_pool()
    try:
        await publish_run_event(redis, run_id, {"status": "loading", "progress": 10})

        graph = build_simulation_graph()
        
        state: SimState = {
            "run_id": run_id,
            "policy_text": "Sample policy",
            "cohorts": [],
            "step": 0,
            "horizon": 1,
            "metrics": [],
            "reactions": [],
            "warnings": []
        }

        # Execute the graph
        node_count = 0
        total_nodes = 12
        
        # Use astream instead of astream_events for simplicity, yields output after each node
        async for output in graph.astream(state, config={"recursion_limit": 50}):
            node_count += 1
            progress = min(90, 10 + int((node_count / total_nodes) * 80))
            await publish_run_event(redis, run_id, {"status": "running", "progress": progress})
        
        await publish_run_event(redis, run_id, {"status": "completed", "progress": 100})
        
        # Update db status and save results
        async with async_session_maker() as session:
            from app.models.run import RunSummary, RunChartData, RunCohortGroup, RunRippleNode, RunRippleEdge, RunStateData, RunTimelineData, RunReport
            
            run = await session.get(SimulationRun, uuid.UUID(run_id))
            if run:
                run.status = "completed"
                run.progress = 100
                
                # Save Summary
                summary = RunSummary(
                    run_id=run.id,
                    sections=[
                        {
                            "title": "Executive Summary",
                            "content": "Generated by LangGraph engine.",
                            "confidence": "Medium",
                            "kind": "modelled"
                        }
                    ],
                    metrics=state.get("metrics", [])
                )
                session.add(summary)
                
                # Save metrics as Chart Data
                # Map state['metrics'] into the dashboard formats
                if state.get("metrics"):
                    metric_data = state["metrics"][-1]
                    session.add(RunChartData(run_id=run.id, chart_type="metric", data_payload={
                        "label": "Household Income Change",
                        "value": f"{metric_data.get('household_income_change', 0)}%",
                        "range": "-5% to 5%",
                        "direction": "negative" if metric_data.get('household_income_change', 0) < 0 else "positive",
                        "kind": "modelled"
                    }))
                    session.add(RunChartData(run_id=run.id, chart_type="metric", data_payload={
                        "label": "Cost of Living Impact",
                        "value": f"{metric_data.get('cost_of_living_change', 0)}%",
                        "range": "0% to 10%",
                        "direction": "negative" if metric_data.get('cost_of_living_change', 0) > 0 else "positive",
                        "kind": "modelled"
                    }))
                    
                    # Income Chart stub
                    session.add(RunChartData(run_id=run.id, chart_type="income", data_payload={"group": "Bottom 20%", "change": -5.0, "low": -7.0, "high": -3.0}))
                    
                    # Jobs stub
                    session.add(RunChartData(run_id=run.id, chart_type="jobs", data_payload={"sector": "Agriculture", "change": metric_data.get('jobs_and_wages_impact', 0), "percentage": -2.0}))
                
                # Save Cohort Groups
                for cohort in state.get("cohorts", [])[:5]: # just top 5 for UI
                    session.add(RunCohortGroup(
                        run_id=run.id,
                        group_id=cohort.get("cohort_id", str(uuid.uuid4())),
                        name=cohort.get("occupation", "Worker") + " in " + cohort.get("region", "Region"),
                        population=str(cohort.get("size", 1000)),
                        description="Cohort analysis",
                        stance_support=30.0,
                        stance_neutral=40.0,
                        stance_oppose=30.0,
                        income_change=-2.0,
                        behaviors=["behavior_change"],
                        confidence="Medium"
                    ))
                
                # Save Ripple Data
                ripple = state.get("ripple", {})
                nodes = ripple.get("nodes", [])
                edges = ripple.get("edges", [])
                
                for node in nodes:
                    session.add(RunRippleNode(
                        run_id=run.id,
                        node_id=node.get("id"),
                        label=node.get("label"),
                        layer=node.get("layer", 0),
                        domain=node.get("domain", "general"),
                        magnitude=node.get("magnitude", "Medium"),
                        confidence=node.get("confidence", "Medium"),
                        kind=node.get("kind", "modelled")
                    ))
                for edge in edges:
                    session.add(RunRippleEdge(
                        run_id=run.id,
                        source_node=edge.get("source"),
                        target_node=edge.get("target"),
                        strength=edge.get("strength", 0.5),
                        lag_months=edge.get("lagMonths", 1),
                        mechanism=edge.get("mechanism", "Direct effect")
                    ))
                
                # Report
                report_data = state.get("report", {})
                if report_data:
                    session.add(RunReport(
                        run_id=run.id,
                        markdown_content="# Policy Analysis Report\n" + str(report_data)
                    ))
                
                session.add(run)
                await session.commit()
                
    except Exception as e:
        traceback.print_exc()
        await publish_run_event(redis, run_id, {"status": "failed", "progress": 0, "error": str(e)})
        async with async_session_maker() as session:
            run = await session.get(SimulationRun, uuid.UUID(run_id))
            if run:
                run.status = "failed"
                run.progress = 0
                session.add(run)
                await session.commit()

async def resume_simulation(run_id: str, approved: bool, feedback: str | None) -> None:
    """Stub: Resume after human checkpoint."""
    pass

async def chat_with_run(run_id: str, message: str) -> str:
    """Stub: LLM Q&A grounded in run context. Returns mock reply."""
    return f"Based on the simulation results for run {run_id}, this policy shows mixed effects across demographics. [Mock response - LangGraph engine not yet connected]"
